name: portfolio
replicaCount: 1

image:
  repository: "sayaligbe/portfolio"
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  port: 80
  type: NodePort

probes:
  enabled: true
  livenessPath: /
  readinessPath: /

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
