---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 8080
      name: {{ .Values.name }}
      targetPort: {{ .Values.service.port }}