---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.name }}-svc
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "ChartTest1.selectorLabels" . | nindent 4 }}
  ports:
    - port: 8080
      name: {{ .Values.name }}
      targetPort: {{ .Values.service.port }}