apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: portfolio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Sarahligbe/rancher-task.git
    targetRevision: HEAD
    path: helm-chart/ChartTest1
  destination:
    server: https://kubernetes.default.svc
    namespace: portfolio
  syncPolicy: 
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true